[client]
bus = session
computer_title = testcomputer
account_name = onward
registration_key = 
url = http://10.183.51.26:8080/message-system
data_path = /tmp/landscape/
log_dir = /tmp/landscape/
log_level = debug
pid_file = /tmp/landscape/landscape-client.pid
ping_url = http://10.183.51.26:8080/ping
